### ISSUE TITLE
Master/Frontend branch do not have the database structure

### ISSUE THREAD

**Issue by Naqu6** [GetInvolvedPA/GetInvolvedPA-Discovery#2]

**Comment by DeckardKane** [comment]
What do you suggest?

**Comment by wlmeng11** [comment]
I cherry-picked Ryan's commit with the models into master and then made one too many merge commits to sync master and frontpage. I'm not sure what to do with the Database branch since it has manual merge conflicts... I guess we can make a new branch off of master?

**Comment by DeckardKane** [comment]
Ah, that explains a lot.

**Comment by wlmeng11** [comment]
Ryan made a new branch off master called backend, so we can abandon the Database branch.
